# Generated by Django 6.0 on 2025-12-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='age',
            field=models.FloatField(max_length=5),
        ),
    ]
